RegisterNetEvent('lsv:playerHighPingWarned')
AddEventHandler('lsv:playerHighPingWarned', function(ping)
	PlaySoundFrontend(-1, 'MP_IDLE_TIMER', 'HUD_FRONTEND_DEFAULT_SOUNDSET', true)
	FlashMinimapDisplay()
	Gui.DisplayPersonalNotification('Your ping is too high ('..ping..' ms).\nPlease fix it or you will be kicked out of session.')
end)